### PR TITLE
24501: fix 5GSIDSTMSI decoding

### PR DESCRIPTION
**Pull request by lukem**
Fix FGSIDSTMSI decoding that was accidentally broken in commit b8aecea

### CODE REVIEW

**Comment by lukem** [comment]
To reproduce:

Run `python ./test.py` or `python ./test/test_mobile.py`, which fail with:
```
  File "test/test_mobile.py", line 360, in test_5gsid
    typ, dec = ident.decode()
               ~~~~~~~~~~~~^^
  File "pycrate_mobile/TS24501_IE.py", line 1235, in decode
    'PLMN': self[3].decode(),
            ^^^^^^^^^^^^^^
AttributeError: 'Uint' object has no attribute 'decode'
```

This fix decodes the 5G-S-TMSI appropriately.

**Comment by mitshell** [comment]
Good catch, and thanks for the PR.
I was mistaken by the github diff view, and re-implemented the same fix in https://github.com/pycrate-org/pycrate/commit/cab9a0475a79c06b1317cc562a774822451c88cb. This latest one also adds the specific 5GSID unit-test as part of the global unit-tests.

**Comment by lukem** [comment]
This PR can be closed given @mitshell's implementation of an equivalent fix in commit cab9a04.
